services:
  claude-code:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-America/Los_Angeles}
    container_name: claude-code
    volumes:
      - type: bind
        source: .
        target: /workspace
        consistency: delegated
      - type: volume
        source: claude-code-bashhistory
        target: /commandhistory
      - type: volume
        source: claude-code-config
        target: /home/node/.claude
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: zsh
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
      - CLAUDE_CONFIG_DIR=/home/node/.claude
      - POWERLEVEL9K_DISABLE_GITSTATUS=true
      - TZ=${TZ:-America/Los_Angeles}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    user: node
    networks:
      - money-graph-network

volumes:
  claude-code-bashhistory:
    name: claude-code-bashhistory
  claude-code-config:
    name: claude-code-config

networks:
  money-graph-network:
    driver: bridge