version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: money-graph-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: money_graph
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - money-graph-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  claude-code:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-America/Los_Angeles}
    container_name: claude-code
    volumes:
      - type: bind
        source: .
        target: /workspace
        consistency: delegated
      - type: volume
        source: claude-code-bashhistory
        target: /commandhistory
      - type: volume
        source: claude-code-config
        target: /home/node/.claude
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: zsh
    environment:
      - NODE_OPTIONS=--max-old-space-size=4096
      - CLAUDE_CONFIG_DIR=/home/node/.claude
      - POWERLEVEL9K_DISABLE_GITSTATUS=true
      - TZ=${TZ:-America/Los_Angeles}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    user: node
    networks:
      - money-graph-network

volumes:
  claude-code-bashhistory:
    name: claude-code-bashhistory
  claude-code-config:
    name: claude-code-config
  postgres_data:
    name: money-graph-postgres-data

networks:
  money-graph-network:
    driver: bridge